with Testy.Tests;

package Requests_Tests is
   use Testy.Tests;

   procedure Test_Valid_Request (T : in out Test_Context);
   procedure Test_Empty_Request (T : in out Test_Context);
   procedure Test_Too_Long_Request (T : in out Test_Context);
   procedure Test_Wrong_Scheme (T : in out Test_Context);
   procedure Test_No_End_CRLF (T : in out Test_Context);
   procedure Test_Embedded_CRLF (T : in out Test_Context);
   procedure Test_Path_Traversal (T : in out Test_Context);
   procedure Test_Encoded_Path_Traversal (T : in out Test_Context);
   procedure Test_Mixed_Encoded_Path_Traversal (T : in out Test_Context);
   procedure Test_Dot_Segment (T : in out Test_Context);
   procedure Test_Encoded_Dot_Segment (T : in out Test_Context);
   procedure Test_Valid_With_Port (T : in out Test_Context);
   procedure Test_Valid_With_Query (T : in out Test_Context);
   procedure Test_Valid_Max_Length (T : in out Test_Context);
   procedure Test_Empty_Host_With_Path (T : in out Test_Context);
   procedure Test_Empty_Host_Bare (T : in out Test_Context);
   procedure Test_Empty_Host_With_Port (T : in out Test_Context);
   procedure Test_Invalid_Percent_Encoding (T : in out Test_Context);
   procedure Test_Valid_Percent_Encoded (T : in out Test_Context);
   procedure Test_Uppercase_Encoded_Traversal (T : in out Test_Context);
   procedure Test_Encoded_Slash_Traversal (T : in out Test_Context);
   procedure Test_CRLF_Only (T : in out Test_Context);
   procedure Test_Garbage_Input (T : in out Test_Context);
   procedure Test_Uppercase_Scheme (T : in out Test_Context);
   procedure Test_Leading_Space_Scheme (T : in out Test_Context);
   procedure Test_No_Line_Ending (T : in out Test_Context);
   procedure Test_LF_Only_Ending (T : in out Test_Context);
   procedure Test_CR_Only_Ending (T : in out Test_Context);
   procedure Test_Bare_Dotdot (T : in out Test_Context);
   procedure Test_Bare_Dot (T : in out Test_Context);
   procedure Test_Uppercase_Encoded_Dot (T : in out Test_Context);
   procedure Test_Valid_No_Path (T : in out Test_Context);
   procedure Test_Valid_Fragment (T : in out Test_Context);
   procedure Test_Valid_Query_Fragment (T : in out Test_Context);
   procedure Test_Valid_UTF8_Encoded (T : in out Test_Context);
   procedure Test_Valid_Encoded_Regular_Char (T : in out Test_Context);
   procedure Test_Valid_Dotdot_Prefix (T : in out Test_Context);
   procedure Test_Valid_Dotdot_Middle (T : in out Test_Context);
   procedure Test_Valid_Dotdot_Suffix (T : in out Test_Context);
   procedure Test_Valid_Dotfile (T : in out Test_Context);
   procedure Test_Valid_Nested_Dotfile (T : in out Test_Context);
   procedure Test_Content_Path_Empty (T : in out Test_Context);
   procedure Test_Content_Path_Trailing_Slash (T : in out Test_Context);
   procedure Test_Content_Path_No_Extension (T : in out Test_Context);
   procedure Test_Content_Path_With_Extension (T : in out Test_Context);
   procedure Test_Content_Path_Nested_With_Extension (T : in out Test_Context);
   procedure Test_Content_Path_Root_Level_File (T : in out Test_Context);
   procedure Test_Content_Path_Nested_No_Extension (T : in out Test_Context);
end Requests_Tests;
